# buildbot-nix scope — wraps upstream services.buildbot-nix.{master,worker}.
#
# Reverse-proxy story: buildbot-nix unconditionally enables nginx with a
# virtualHost on the configured domain. To coexist with the fleet's
# Caddy (which owns 80/443 + ACME + the *.lab.internal naming scheme),
# we override the nginx listen to bind on 127.0.0.1:8011, then declare
# the service in `_data/services.nix` so Caddy auto-creates an https
# vhost reverse-proxying https://buildbot.lab.internal → 127.0.0.1:8011.
# useHTTPS=true tells buildbot its public URL is https (Caddy
# terminates), so webhook + OAuth redirect URIs are constructed
# correctly.
#
# Bootstrap order (after first activation):
#   1. In Forgejo UI: Site Admin → Applications → New OAuth2 App.
#      Redirect URI: https://buildbot.lab.internal/auth/login.
#   2. Set `forgejo.oauthId` to the clientId (NOT secret; commit-safe).
#   3. Re-encrypt `buildbot-forgejo-oauth-secret.age` with the secret.
#   4. Generate Forgejo API token (admin scope) → re-encrypt as
#      `buildbot-forgejo-token.age`.
#   5. Tag target repos with topic "fleet-ci" (or use repoAllowlist).
#   6. Run scripts/garage-bootstrap-cluster.sh → re-encrypt
#      `garage-ci-creds.age` with the minted AWS_*.
#   7. Push fleet; CI re-deploys lab; buildbot auto-creates webhooks.
#
# Coexists with forgejo-actions: different services, different ports,
# no overlap. Both can run on lab simultaneously.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.nixfleet.ciRunner.buildbotNix;

  # Worker JSON materialized at startup so the password isn't world-readable
  # in the nix store. Generated by ExecStartPre into the master state dir.
  workersJsonPath = "/var/lib/buildbot-master/workers.json";

  # Loopback port for buildbot's nginx vhost; Caddy fronts on 443.
  # Must match the entry in modules/_data/services.nix (service "buildbot").
  internalPort = 8011;

  # nix-daemon post-build-hook: pushes every successful build to Garage.
  # $OUT_PATHS is set by the daemon to the just-built store paths.
  pushHook = pkgs.writeShellScript "buildbot-cache-push" ''
    set -euf
    export IFS=' '
    exec ${config.nix.package}/bin/nix copy \
      --to "${cfg.cachePush.s3Url}" $OUT_PATHS
  '';
in
{
  # NOTE: the upstream buildbot-nix modules (buildbot-master + buildbot-worker)
  # are imported globally from _fleet-modules.nix — they can't be imported
  # here because fleetInputs is a config-dependent arg and `imports` is
  # evaluated before config (infinite-recursion trap).
  imports = [ ./options.nix ];

  config = lib.mkMerge [
    # Always-evaluated: enforce post-build-hook authoritatively. mkForce
    # makes the value reflect the current scope state including explicit
    # null when disabled, which prevents the "stale hook from a prior
    # activation breaks every subsequent nix build" failure mode the
    # daemon would otherwise hit.
    {
      nix.settings.post-build-hook = lib.mkForce (
        if cfg.enable && cfg.cachePush.enable then "${pushHook}" else null
      );
    }

    # Full buildbot wiring when enabled.
    (lib.mkIf cfg.enable {
      assertions = [
        {
          assertion = cfg.cachePush.enable -> cfg.cachePush.s3Url != "";
          message = "nixfleet.ciRunner.buildbotNix.cachePush.enable requires cachePush.s3Url.";
        }
        {
          assertion = cfg.forgejo.oauthId != "";
          message = "nixfleet.ciRunner.buildbotNix requires forgejo.oauthId (create OAuth app in Forgejo first).";
        }
      ];

      services.buildbot-nix.master = {
        enable = true;
        inherit (cfg) domain admins allowUnauthenticatedControl;
        useHTTPS = true; # Caddy terminates; webhook + OAuth URLs are https.
        workersFile = workersJsonPath;
        inherit (cfg.master) dbUrl;

        authBackend = "gitea";
        gitea = {
          enable = true;
          inherit (cfg.forgejo) instanceUrl;
          inherit (cfg.forgejo) oauthId topic;
          inherit (cfg.forgejo) oauthSecretFile;
          inherit (cfg.forgejo) webhookSecretFile;
          inherit (cfg.forgejo) tokenFile;
          inherit (cfg.forgejo) repoAllowlist;
        };
      };

      services.buildbot-nix.worker = {
        enable = true;
        workers = cfg.workerCount;
        workerPasswordFile = cfg.worker.passwordFile;
      };

      # Override buildbot-nix's nginx vhost to bind on a loopback port.
      # Caddy in _data/services.nix handles TLS + the public hostname.
      services.nginx.virtualHosts.${cfg.domain} = {
        listen = lib.mkForce [
          {
            addr = "127.0.0.1";
            port = internalPort;
            ssl = false;
          }
        ];
        forceSSL = lib.mkForce false;
        addSSL = lib.mkForce false;
        enableACME = lib.mkForce false;
      };

      # Materialize workersFile from the worker password secret AT
      # ACTIVATION TIME — must happen before buildbot-master.service
      # touches its LoadCredential=buildbot-nix-workers source path.
      # ExecStartPre runs AFTER LoadCredential in systemd's order, so
      # writing the file in preStart is too late (was hitting
      # status=243/CREDENTIALS on first deploy). Activation scripts
      # run after agenix-decrypted files exist in /run/agenix/, so the
      # worker password is available here.
      system.activationScripts.buildbot-workers-json = {
        deps = [ "agenix" ];
        text = ''
          set -euf
          install -d -m 0755 /var/lib/buildbot-master
          pass=$(cat ${cfg.worker.passwordFile})
          cores=${if cfg.workerCount == 0 then "$(${pkgs.coreutils}/bin/nproc)" else toString cfg.workerCount}
          umask 077
          cat > /var/lib/buildbot-master/workers.json <<EOF
          [{"name": "${config.networking.hostName}", "pass": "$pass", "cores": $cores}]
          EOF
          chmod 600 /var/lib/buildbot-master/workers.json
        '';
      };

      # Provision local postgres DB + user when requested. Peer auth via
      # unix socket — buildbot's system user maps to postgres role.
      services.postgresql = lib.mkIf cfg.master.useLocalPostgres {
        ensureDatabases = [ "buildbot" ];
        ensureUsers = [
          {
            name = "buildbot";
            ensureDBOwnership = true;
          }
        ];
      };

      # nix-daemon picks up AWS_ACCESS_KEY_ID/SECRET from EnvironmentFile
      # and passes them to the post-build-hook subprocess (→ nix copy).
      systemd.services.nix-daemon.serviceConfig = lib.mkIf cfg.cachePush.enable {
        EnvironmentFile = cfg.cachePush.credentialsFile;
        # Disable AWS SDK's mandatory new-style request/response
        # checksums (CRC32 by default in recent SDKs). Garage and most
        # other S3-compatible servers don't support them and reject
        # uploads with "Bad request: invalid checksum algorithm".
        # Falls back to the SDK's legacy behaviour, which Garage handles.
        Environment = [
          "AWS_REQUEST_CHECKSUM_CALCULATION=when_required"
          "AWS_RESPONSE_CHECKSUM_VALIDATION=when_required"
        ];
      };

      networking.firewall.allowedTCPPorts = lib.mkIf cfg.openFirewall [
        9989 # master↔worker pb protocol (only needed if worker is off-host)
      ];

      nixfleet.persistence.directories = [
        "/var/lib/buildbot-master"
        "/var/lib/buildbot-worker"
      ];
    })
  ];
}
